services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
