services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-dev
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:PLACEHOLDER
