import type { Metadata } from "next";
import "../globals.css";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_PROJECT_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className="h-full">
        <AuthProvider>
          <main className="flex w-full h-full items-center justify-center">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
